// angular/src/examples/customDisplayLogic/customDisplayLogic.component.ts
import { Component, Input } from '@angular/core';
import { USERSNAP_PROJECT_API_KEY } from '../../constants';
import { UsersnapService } from '../../services/usersnap.service';

@Component({
  selector: 'app-custom-display-logic',
  templateUrl: './customDisplayLogic.component.html',
  providers: [UsersnapService]
})
export class CustomDisplayLogicComponent {
  @Input() shouldShow = true;

  constructor(private usersnapService: UsersnapService) { }

  /**
   * In order to have custom logic to show your widget you need to make sure that
   * in the dashboard configuration of your widget in the "Display" tab you have
   * audience "Nobody". Then you open your feedback button or widget whenever you need.
   */
  ngOnInit() {
    this.usersnapService.initialize().then((usersnapApi) => {
      if (this.shouldShow) {
        usersnapApi.show(USERSNAP_PROJECT_API_KEY);
      }
    });
  }
}

<div>Custom logic for displaying the widget or feedback button</div>

// react-typescript/src/examples/CustomDisplayLogic.tsx
import { useEffect } from 'react'
import { USERSNAP_PROJECT_API_KEY } from '../constants'
import { useUsersnapApi } from '../useUsersnapApi'

/**
 * In order to have custom logic to show your widget you need to make sure that
 * in the dashboard configuration of your widget in the "Display" tab you have
 * audience "Nobody". Then you open your feedback button or widget whenever you need.
 */
export default function CustomDisplayLogic({ shouldShow = true }) {
  const usersnapApi = useUsersnapApi()

  useEffect(() => {
    if (usersnapApi && shouldShow) {
      usersnapApi.show(USERSNAP_PROJECT_API_KEY)
    }
  }, [usersnapApi, shouldShow])

  return <div>Custom logic for displaying the widget or feedback button</div>
}
