// angular/src/examples/passInitialValues/passInitialValues.component.ts
import { Component, Input } from "@angular/core";
import { UsersnapService } from "../../services/usersnap.service";
import type { SpaceOpenEventCallback } from "@usersnap/browser";

@Component({
	selector: "app-pass-initial-values",
	templateUrl: "./passInitialValues.component.html",
	providers: [UsersnapService],
})
export class PassInitialValuesComponent {
	@Input() labels = ["Bug"];
	@Input() email = "user@mail.com";
	@Input() assignee = "assignee@mail.com";
	@Input() rating = "5";

	constructor(private usersnapService: UsersnapService) {}

	/**
	 * You can define initial values for a few fields in your widget.
	 * Important that those fields must exist in your widget.
	 * Please note that "rating" field is available only for
	 * NPS, CSAT and Customer Engagement
	 */
	ngOnInit() {
		this.usersnapService.initialize().then((usersnapApi) => {
			usersnapApi.on("open", this.handleOpenWidget);
		});
	}

	ngOnDestroy() {
		if (this.usersnapService.usersnapApi) {
			this.usersnapService.usersnapApi.off("open", this.handleOpenWidget);
		}
	}

	private handleOpenWidget: SpaceOpenEventCallback = (event) => {
		event.api.setValue("labels", this.labels);
		event.api.setValue("visitor", this.email);
		event.api.setValue("assignee", this.assignee);
		event.api.setValue("rating", this.rating);
	};
}

<div>Pass initial values to widget</div>

// react-typescript/src/examples/PassInitialValues.tsx
import { useEffect } from "react";
import { useUsersnapApi } from "../useUsersnapApi";
import type { SpaceOpenEventCallback } from "@usersnap/browser";

/**
 * You can define initial values for a few fields in your widget.
 * Important that those fields must exist in your widget.
 * Please note that "rating" field is available only for
 * NPS, CSAT and Customer Engagement
 */
export default function PassInitialValues({
	labels = ["Bug"],
	email = "user@mail.com",
	assignee = "assignee@mail.com",
	rating = 5,
}) {
	const usersnapApi = useUsersnapApi();

	useEffect(() => {
		if (!usersnapApi) {
			return;
		}

		const handleOpenWidget: SpaceOpenEventCallback = (event) => {
			console.log(event.api);
			event.api.setValue("labels", labels);
			event.api.setValue("visitor", email);
			event.api.setValue("assignee", assignee);
			event.api.setValue("rating", rating.toString());
		};
		usersnapApi.on("open", handleOpenWidget);

		return () => usersnapApi.off("open", handleOpenWidget);
	}, [usersnapApi, labels, email, assignee, rating]);
}
