// vue-js/src/App.vue
<script>
import UsernapProvider from './components/UsersnapProvider.vue'
import CustomButton from './examples/CustomButton.vue'
import CustomDisplayLogic from './examples/CustomDisplayLogic.vue'
import PassInitialValues from './examples/PassInitialValues.vue'
import PassHiddenValues from './examples/PassHiddenValues.vue'
import WidgetApiEvents from './examples/WidgetApiEvents.vue'

export default {
  data() {
    return {
      currentExample: 'basic',
    }
  },
  methods: {
    setCurrentExample(example) {
      this.currentExample = example;
    }
  },
  components: {
    UsernapProvider,
    CustomButton,
    CustomDisplayLogic,
    PassInitialValues,
    WidgetApiEvents,
    PassHiddenValues,
  }
}
</script>

<template>
  <div class="wrapper">
    <header>
      <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />
    </header>

    <div class="buttons">
        <button @click="setCurrentExample('basic')">Basic</button>
        <button @click="setCurrentExample('customButton')">Custom button</button>
        <button @click="setCurrentExample('onlyForLoggedInUsers')">Only for logged in users</button>
        <button @click="setCurrentExample('onlyWithCertainEmails')">Only with certain emails</button>
        <button @click="setCurrentExample('customDisplayLogic')">Custom display logic</button>
        <button @click="setCurrentExample('passInitialValues')">Pass initial values</button>
        <button @click="setCurrentExample('passHiddenValues')">Pass hidden values</button>
        <button @click="setCurrentExample('widgetApiEvents')">Widget API events</button>
        <button @click="setCurrentExample('nativeScreenshot')">Native screenshot</button>
        <button @click="setCurrentExample('nativeScreenshotInNewTab')">Native screenshot in new tab</button>
        <button @click="setCurrentExample('otherWidgetOptions')">Other widget options</button>
      </div>

    <main>
      <UsernapProvider v-if="currentExample === 'basic'">
        <div>Basic installation</div>
      </UsernapProvider>
      <UsernapProvider v-if="currentExample === 'customButton'">
        <CustomButton />
      </UsernapProvider>
      <UsernapProvider :initParams="{
        /**
        * 'userId' should be non-falsy value in order for the widget
        * to consider the current user as logged in one
        */
        user: { userId: '123' }
      }" v-if="currentExample === 'onlyForLoggedInUsers'">
        <div>Only logged in users should see that</div>
      </UsernapProvider>
      <UsernapProvider :initParams="{
        /**
        * 'email' should be a string which will be compared
        * to the list of allowed or not-allowed emails
        */
        user: { email: 'user@mail.com' }
      }" v-if="currentExample === 'onlyWithCertainEmails'">
        <div>Only users with included emails should see that</div>
      </UsernapProvider>
      <UsernapProvider v-if="currentExample === 'customDisplayLogic'">
        <CustomDisplayLogic />
      </UsernapProvider>
      <UsernapProvider v-if="currentExample === 'passInitialValues'">
        <PassInitialValues />
      </UsernapProvider>
      <UsernapProvider v-if="currentExample === 'passHiddenValues'">
        <PassHiddenValues />
      </UsernapProvider>
      <UsernapProvider v-if="currentExample === 'widgetApiEvents'">
        <WidgetApiEvents />
      </UsernapProvider>
      <UsernapProvider :initParams="{
        /**
        * 'nativeScreenshot' should be 'true' value or '{ target: '_self' }'
        */
        nativeScreenshot: true
      }" v-if="currentExample === 'nativeScreenshot'">
        <div>Native screenshot</div>
      </UsernapProvider>
      <UsernapProvider :initParams="{
        /**
        * 'nativeScreenshot' should be an object '{ target: '_blank' }'
        */
        nativeScreenshot: { target: '_blank' }
      }" v-if="currentExample === 'nativeScreenshotInNewTab'">
        <div>Native screenshot in new tab</div>
      </UsernapProvider>
      <UsernapProvider :initParams="{
          collectGeoLocation: 'none', // whether to collect geo location when submitting feedback, other values are null and 'all'
          enableScreenshot: false, // whether to enable widget screenshot
          useLocalStorage: false, // whether allowed to use user's local storage
          useSystemFonts: true, // whether widget should use browser default font rather than loading external one
          locale: 'de' // force widget language
        }" v-if="currentExample === 'otherWidgetOptions'">
        <div>Other widget options</div>
        <ul>
            <li>collectGeoLocation</li>
            <li>enableScreenshot</li>
            <li>useLocalStorage</li>
            <li>useSystemFonts</li>
            <li>locale</li>
        </ul>
      </UsernapProvider>
    </main>
  </div>
</template>

<style>
@import './assets/base.css';

#app {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;

  font-weight: normal;
}

header {
  line-height: 1.5;
  width: 100%;
}

.buttons {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}

button {
  background: none;
  border: 1px solid black;
  margin-right: 10px;
  margin-bottom: 10px;
  cursor: pointer;
}

main {
  font-size: 25px;
  margin-top: 20px;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  body {
    display: flex;
    place-items: center;
  }

  #app {
    padding: 0 2rem;
  }

  .wrapper {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  header {
    display: flex;
    place-items: center;
  }
}
</style>

// react-js/src/App.js
import { useState } from 'react';
import logo from './logo.svg';
import './App.css';
import { UsersnapProvider } from './UsersnapContext';
import CustomButton from './examples/CustomButton';
import CustomDisplayLogic from './examples/CustomDisplayLogic';
import PassInitialValues from './examples/PassInitialValues';
import WidgetApiEvents from './examples/WidgetApiEvents';
import PassHiddenValues from './examples/PassHiddenValues';

function App() {
  const [currentExample, setCurrentExample] = useState('basic')

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
      </header>
      <div>
        <button onClick={() => setCurrentExample('basic')}>Basic</button>
        <button onClick={() => setCurrentExample('customButton')}>Custom button</button>
        <button onClick={() => setCurrentExample('onlyForLoggedInUsers')}>Only for logged in users</button>
        <button onClick={() => setCurrentExample('onlyWithCertainEmails')}>Only with certain emails</button>
        <button onClick={() => setCurrentExample('customDisplayLogic')}>Custom display logic</button>
        <button onClick={() => setCurrentExample('passInitialValues')}>Pass initial values</button>
        <button onClick={() => setCurrentExample('passHiddenValues')}>Pass hidden values</button>
        <button onClick={() => setCurrentExample('widgetApiEvents')}>Widget API events</button>
        <button onClick={() => setCurrentExample('nativeScreenshot')}>Native screenshot</button>
        <button onClick={() => setCurrentExample('nativeScreenshotInNewTab')}>Native screenshot in new tab</button>
        <button onClick={() => setCurrentExample('otherWidgetOptions')}>Other widget options</button>
      </div>
      <div className="examples">
        {currentExample === 'basic' && (
          <UsersnapProvider>
            <div>Basic installation</div>
          </UsersnapProvider>
        )}
        {currentExample === 'customButton' && (
          <UsersnapProvider>
            <CustomButton />
          </UsersnapProvider>
        )}
        {currentExample === 'onlyForLoggedInUsers' && (
          /**
           * "userId" should be non-falsy value in order for the widget
           * to consider the current user as logged in one
           */
          <UsersnapProvider initParams={{ user: { userId: '123' }}}>
            <div>Only logged in users should see that</div>
          </UsersnapProvider>
        )}
        {currentExample === 'onlyWithCertainEmails' && (
          /**
           * "email" should be a string which will be compared
           * to the list of allowed or not-allowed emails
           */
          <UsersnapProvider initParams={{ user: { email: 'user@mail.com' }}}>
            <div>Only users with allowed emails should see that</div>
          </UsersnapProvider>
        )}
        {currentExample === 'customDisplayLogic' && (
          <UsersnapProvider>
            <CustomDisplayLogic />
          </UsersnapProvider>
        )}
        {currentExample === 'passHiddenValues' && (
          <UsersnapProvider>
            <PassHiddenValues />
          </UsersnapProvider>
        )}
        {currentExample === 'passInitialValues' && (
          <UsersnapProvider>
            <PassInitialValues />
          </UsersnapProvider>
        )}
        {currentExample === 'widgetApiEvents' && (
          <UsersnapProvider>
            <WidgetApiEvents />
          </UsersnapProvider>
        )}
        {currentExample === 'nativeScreenshot' && (
          /**
           * "nativeScreenshot" should be "true" value or "{ target: '_self' }"
           */
          <UsersnapProvider initParams={{ nativeScreenshot: true }}>
            <div>Native screenshot</div>
          </UsersnapProvider>
        )}
        {currentExample === 'nativeScreenshotInNewTab' && (
          /**
           * "nativeScreenshot" should be object "{ target: '_blank' }"
           */
          <UsersnapProvider initParams={{ nativeScreenshot: { target: '_blank' } }}>
            <div>Native screenshot in new tab</div>
          </UsersnapProvider>
        )}
        {currentExample === 'otherWidgetOptions' && (
          <UsersnapProvider initParams={{
            collectGeoLocation: 'none', // whether to collect geo location when submitting feedback, other values are "null" and "'all"
            enableScreenshot: false, // whether to enable widget screenshot
            useLocalStorage: false, // whether allowed to use user's local storage
            useSystemFonts: true, // whether widget should use browser default font rather than loading external one
            locale: 'de' // force widget language
          }}>
            <div>Other widget options</div>
            <ul>
                <li>collectGeoLocation</li>
                <li>enableScreenshot</li>
                <li>useLocalStorage</li>
                <li>useSystemFonts</li>
                <li>locale</li>
            </ul>
          </UsersnapProvider>
        )}
      </div>
    </div>
  );
}

export default App;
