// react-typescript/src/examples/PassInitialValues.tsx
import { useEffect } from 'react'
import { useUsersnapApi } from '../UsersnapContext'

/**
 * You can define initial values for a few fields in your widget.
 * Important that those fields must exist in your widget.
 * Please note that "rating" field is available only for
 * NPS, CSAT and Customer Engagement
 */
export default function PassInitialValues({ labels = ['Bug'], email = 'user@mail.com', assignee = 'assignee@mail.com', rating = 5 }) {
    const usersnapApi = useUsersnapApi()

    useEffect(() => {
        if (!usersnapApi) {
            return
        }

        const handleOpenWidget = (event: any) => {
            event.api.setValue('labels', labels);
            event.api.setValue('visitor', email);
            event.api.setValue('assignee', assignee);
            event.api.setValue('rating', rating);
        }
        usersnapApi.on('open', handleOpenWidget);

        return () => usersnapApi.off('open');
    }, [usersnapApi, labels, email, assignee, rating])

    return <div>Pass initial values to widget</div>
}

// vue-js/src/examples/PassInitialValues.vue
<script>
/**
 * You can define initial values for a few fields in your widget.
 * Important that those fields must exist in your widget.
 * Please note that "rating" field is available only for
 * NPS, CSAT and Customer Engagement
 */
export default {
    inject: ['usersnapApi'],
    props: {
        labels: {
            type: Array,
            default: ['Bug'],
        },
        email: {
            type: String,
            default: 'user@mail.com',
        },
        assignee: {
            type: String,
            default: 'assignee@mail.com',
        },
        rating: {
            type: Number,
            default: 5,
        }
    },
    methods: {
        handleOpenWidget(event) {
            event.api.setValue('labels', this.labels);
            event.api.setValue('visitor', this.email);
            event.api.setValue('assignee', this.assignee);
            event.api.setValue('rating', this.rating);
        }
    },
    created() {
        const unwatch = this.$watch('usersnapApi', (usersnapApi, oldVal) => {
            if (!oldVal && usersnapApi) {
                usersnapApi.on('open', this.handleOpenWidget);
                
                unwatch()
            }
        }, { immediately: true })
    },
    beforeUnmount() {
        if (this.usersnapApi) {
            this.usersnapApi.off('open', this.handleOpenWidget)
        }
    }
}
</script>

<template>
    <div>Pass initial values to widget</div>
</template>
