// react-js/src/examples/PassHiddenValues.js
import { useEffect } from 'react'
import { useUsersnapApi } from '../UsersnapContext'

/**
 * You can define hidden values for some fields which are not
 * visible in your widget.
 */
export default function PassHiddenValues({
    labels = ['Bug', 'Urgent'],
    email = 'user@mail.com',
    assignee = 'assignee@mail.com',
    custom = {
        importantData: 'From Super user'
    }
}) {
    const usersnapApi = useUsersnapApi()

    useEffect(() => {
        if (!usersnapApi) {
            return
        }

        const handleOpenWidget = (event) => {
            event.api.setValue('labels', labels);
            event.api.setValue('visitor', email);
            event.api.setValue('assignee', assignee);
            event.api.setValue('custom', custom);
        }
        usersnapApi.on('open', handleOpenWidget);

        return () => usersnapApi.off('open', handleOpenWidget);
    }, [usersnapApi, labels, email, assignee, custom])

    return <div>Pass initial values to widget</div>
}

// vue-js/src/examples/PassHiddenValues.vue
<script>
/**
 * You can define hidden values for some fields which are not
 * visible in your widget.
 */
export default {
    inject: ['usersnapApi'],
    props: {
        labels: {
            type: Array,
            default: ['Bug', 'Urgent'],
        },
        email: {
            type: String,
            default: 'user@mail.com',
        },
        assignee: {
            type: String,
            default: 'assignee@mail.com',
        },
        custom: {
            type: null,
            default: {
                importantData: 'From Super user'
            },
        }
    },
    methods: {
        handleOpenWidget(event) {
            console.log('here')
            event.api.setValue('labels', this.labels);
            event.api.setValue('visitor', this.email);
            event.api.setValue('assignee', this.assignee);
            event.api.setValue('custom', this.custom);
        }
    },
    created() {
        console.log('now')
        const unwatch = this.$watch('usersnapApi', (usersnapApi, oldVal) => {
            console.log('usersnapApi')
            if (!oldVal && usersnapApi) {
                usersnapApi.on('open', this.handleOpenWidget);
                
                unwatch()
            }
        }, { immediately: true })
    },
    beforeUnmount() {
        if (this.usersnapApi) {
            this.usersnapApi.off('open', this.handleOpenWidget)
        }
    }
}
</script>

<template>
    <div>Pass hidden values to widget</div>
</template>
